version: '3'
rpc:
    listen: 'tcp://127.0.0.1:6001'
jobs:
    pool:
        num_workers: 2
        max_worker_memory: 100
    consume: [ "kafka" ]
    pipelines:
      kafka:
        driver: kafka
        config:
          auto_create_topics_enable: true
          consumer_options:
            topics: [ "phones" ]
server:
    command: 'php app.php'
    relay: pipes

kafka:
  brokers: [ "127.0.0.1:9092" ]
